name: bayes
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib=3.0.2
  - pymc3=3.6
  - pandas=0.25.0
  - seaborn=0.9
  - numpy=1.15.0
  - scipy=1.1
  - graphviz=2.38.0
  - python-graphviz=0.8.4
  - pip=20.2.4
  - mkl-service
  - pip:
    - arviz==0.3.1
    - watermark==2.0.1
